### ISSUE TITLE
Linking to a supporting project

### ISSUE THREAD

**Issue by brycefisher** [dpc/docker-source-checksum#4]
So, I'm working on a docker image for monorepos (or even standalone projects) to help with my prefered workflow. I'm super excited about this project!

Here's two other projects in this space that I think make a killer combination:
 - [docker-image-tag](https://github.com/stefanwalther/docker-image-tag) (written in go) -- this allows you to _check_ if a given tag exists for a remote image before calling docker build
 - [kaniko](https://github.com/GoogleContainerTools/kaniko) -- allows you to build docker-formatted OCI images without using docker....making it perfect to use _in_ docker _in_ CI

Taken together these three projects should allow me to do this:
 1. Use `docker-source-checksum` to calculate the docker tag I would build at this point in git history in CI
 2. Use `docker-image-tag` to see if the tag exists without doing a ton of extra network IO
 3. Use `kaniko` to build the image if the tag does not already exist, and to push that tag out
 4. Use the resulting docker image for the rest of my CI pipeline for testing/deployment to production (say fly.io)

There's no particular action item here, just wanted to point out to anyone interested in this project that those other two projects are probably interesting to them as well.

**Comment by dpc** [comment]
```
if DOCKER_CLI_EXPERIMENTAL=enabled docker manifest inspect $TAG_NAME > /dev/null; then
  echo "$TAG_NAME already exists in the repository. Skipping build and push"
  exit 0
fi
```

for checking image

**Comment by brycefisher** [comment]
Does that check locally or at the remote registry? (Also, this is awesome!!)
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dpc** [comment]
I'm using it for remote repository.
